from grafo import Graph

if __name__ == "__main__":
    G = Graph()
    G.addVertex('a')
    G.addVertex('b')
    G.addVertex('c')
    G.addVertex('d')
    G.addVertex('e')
    G.addVertex('f')
    # print("GetVertices", G.getVertices())
    # print("G.Vertices", G.vertices)
    # print(G.vertices['a'].id)
    # print("ConnectedTo", G.vertices['a'].connectedTo)
    G.addEdge('a', 'b', 3)
    G.addEdge('a', 'c', 2)
    G.addEdge('c', 'd', 8)
    G.addEdge('b', 'e', 5)
    G.addEdge('e', 'f', 4)
    #print("ConnectedTo:", G.vertices['a'].connectedTo)
    print("GetEdges", G.getEdges())
    print(G.getVertices())
    # print("Largura:")
    # print(G.bfs('a'))
    #print("Profundidade:")
    #print(G.dfs('a'))
    #print("LOUCURA:")
    #print(G.dijkstra('a'))
    del G